name: "Commit messages adheres to guidelines at https://goo.gl/p2fr5Q"

on: [pull_request]

env:
  NODE_VERSION: lts/*

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Last 100 commits should be enough for a PR
          fetch-depth: 100
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Validate commit messages
        run: |
          echo "::add-matcher::.github/workflows/commit-lint-problem-matcher.json"
          git log --oneline ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -v -e fixup -e squash | awk '{ print $1 }' |  xargs npx -q core-validate-commit --no-validate-metadata --tap
